# Generated by Django 5.2 on 2025-05-03 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_remove_feedback_is_positive_feedback_private_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='private_comment',
        ),
    ]
