# Generated by Django 5.2 on 2025-04-11 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_contact_number_alter_userprofile_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_activity',
            new_name='last_active',
        ),
    ]
