# Generated by Django 5.0.6 on 2025-04-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
